sudo: required
services:
    - docker
    
before_install:
    - docker build -t griffinsibm/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true griffinsibm/react-test npm run test -- --coverage
    
after_success:
    - docker build -t griffinsibm/multi-client ./client
    - docker build -t griffinsibm/multi-nginx ./nginx
    - docker build -t griffinsibm/multi-server ./server
    - docker build -t griffinsibm/multi-worker ./worker
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take these images and push them to Docker Hub
    - docker push griffinsibm/multi-client
    - docker push griffinsibm/multi-nginx
    - docker push griffinsibm/multi-server
    - docker push griffinsibm/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-546941218646"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
